# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnuncio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='state_documents.Documento')),
                ('fecha_presentacion_ofertas', models.CharField(blank=True, max_length=4000, null=True)),
                ('fecha_apertura_ofertas', models.CharField(blank=True, max_length=4000, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('ambito_geografico', models.CharField(blank=True, max_length=4000, null=True)),
                ('materias_anuncio', models.CharField(blank=True, max_length=4000, null=True)),
                ('materias_cpv', models.CharField(blank=True, max_length=4000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=4000, null=True)),
                ('materias_licitaciones', models.ManyToManyField(null=True, related_name='materias_licitaciones', to='state_documents.Materia')),
            ],
            bases=('state_documents.documento',),
        ),
        migrations.CreateModel(
            name='DocumentoBORME',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='state_documents.Documento')),
                ('departamento_anuncio', models.CharField(blank=True, max_length=4000, null=True)),
                ('num_anuncio', models.CharField(blank=True, max_length=4000, null=True)),
                ('anuncio_id', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            bases=('state_documents.documento',),
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tramitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='documentoanuncio',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state_documents.Modalidad'),
        ),
        migrations.AddField(
            model_name='documentoanuncio',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state_documents.Precio'),
        ),
        migrations.AddField(
            model_name='documentoanuncio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state_documents.Tipo'),
        ),
        migrations.AddField(
            model_name='documentoanuncio',
            name='tramitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state_documents.Tramitacion'),
        ),
    ]
